apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mevy3hyms-dotnet-basic
  janus-idp.io/tekton: mevy3hyms-dotnet-basic
  backstage.io/kubernetes-id: mevy3hyms-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mevy3hyms-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
